### ISSUE TITLE
[Suggestion] Make "freelook" disabled by default

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#22]
Title says it all

**Comment by adrisj7** [comment]
Hmm how come?

**Comment by BlueBurgersTDD** [comment]
It just feels better, I have no idea why

**Comment by adrisj7** [comment]
hah gotcha, will definitely consider it

**Comment by BlueBurgersTDD** [comment]
Also the stream is in 50 minutes right?

**Comment by BlueBurgersTDD** [comment]
im not good at timezones

**Comment by adrisj7** [comment]
Yessir, from now that's exactly 37 minutes.
