### ISSUE TITLE
"Closest Block" Task Sucks (Particularly Lava Liquid Collection)

### ISSUE THREAD

**Issue by adrisj7** [toccatina/altoclef#33]
There's something fundamentally wrong with the "do to closest block" task, as it's inefficient and kinda stupid.

When building a portal, liquid collection can often get stuck.
When mining diamonds, many diamonds are left out.

**Comment by voruti** [comment]
> When mining diamonds, many diamonds are left out.

Can confirm; I think almost half of the diamonds are left out.

**Comment by adrisj7** [comment]
Example: Took 5 minutes to find water
https://youtu.be/_kb0x-szNso
Time: 42:30

**Comment by adrisj7** [comment]
Thankfully the "bot missing diamonds" bug is an easy fix. The timers that check for failure use real world time instead of in game ticks, so if you pause the game/lag for a bit they get set off, detecting that the player hasn't made any progress. Will be fixed under [codebase-fixes](https://github.com/toccatina/altoclef/tree/codebase-fixes).

Unfortunately the lava collection/water collection is another big issue, will need to deconstruct what I'm currently doing.

**Comment by adrisj7** [comment]
Picture of bot not grabbing closest water source from #16:
![](https://user-images.githubusercontent.com/58081413/119259543-07e4ed80-bbcf-11eb-8af5-bd174950f8c7.png)

**Comment by adrisj7** [comment]
Here's what I think is happening with the closest block/item task (and why I'm using it instead of baritone's MineProcess)

The task caches the heuristic "travel distance score" of each item it tries to navigate to. If it finds a closer object it will attempt that object instead, comparing its heuristic to other objects. When re-considering closer objects, it will check the cached heuristic chain to determine whether to proceed.

The issue with this is that the heuristic can become outdated real fast: If you cache a heuristic when you're really far away from something, when you get closer the bot will completely ignore the item _even if it's super duper close_.

The reason why I don't just use baritone's MineProcess is because I need to keep track of _which_ item I'm accessing, so I can blacklist if I fail to reach it. Baritone's mineprocess just goes after every single ore it finds via A* (and this is way better in every other aspect, but it doesn't give me "the current target" just yet).

Will see if I can maybe re-write the task to use baritone goals and figure out which item is currently being pursued.

**Comment by adrisj7** [comment]
Sort of fixed in commit [codebase-fixes/ada654da605708903a7addd5cd79f10d026f7a3e](https://github.com/toccatina/altoclef/commit/ada654da605708903a7addd5cd79f10d026f7a3e).

The solution wasn't elegant but it improved the general case: The bot also re-considers going to another object if it's moved much closer to it than before. This fixes the mentioned issue of the heuristics being completely out of date by position, but also makes the edge case (where you have two objects and can get stuck bouncing back between them) a little slower, as some bouncing back+forth will be done (but not too much, and it is an edge case so making that a little slower is worth it)

**Comment by SylveonBottle** [comment]
https://clips.twitch.tv/AmazonianFaintPenguinTooSpicy-s_308XIy_5YhPkb-

Can we re-open this? Or shall I make a new issue?
