### ISSUE TITLE
Bot can not access Nether on tasks other than "@gamer"

### ISSUE THREAD

**Issue by EnigmaAlliance** [toccatina/altoclef#38]
while doing "get" or "butler" task, the bot will not build nether portals or use existing portals to travel cross-dimensionally. tested using the "@get quartz" command

**Comment by adrisj7** [comment]
Need to implement [DefaultGoToDimensionTask](https://github.com/adrisj7-AltoClef/altoclef/blob/main/src/main/java/adris/altoclef/tasks/DefaultGoToDimensionTask.java)

**Comment by adrisj7** [comment]
Implemented simple Overworld <--> Nether travel in [codebase-fixes/commit 3bcd04338400d0a6912ee1207dd53db2e86fb88d](https://github.com/toccatina/altoclef/commit/3bcd04338400d0a6912ee1207dd53db2e86fb88d).

Two separate and really simple strategies added for traveling to the nether. Escaping the nether right now is the same every time and assumes that you left a portal or were near one at some point, but will add strategies for that as well at some point.
