### ISSUE TITLE
Simplify build process

### ISSUE THREAD

**Issue by adrisj7** [toccatina/altoclef#41]
Currently our users don't need to copy over the fabritone jar to TEST the project, but to BUILD it they gotta open up the fabritone project. That's annoying.

When building a full jar the process should be easy. If at all possible, everything should be merged into one jar.

If not, at least every dependent jar should be included somewhere in the build folder.

**Comment by voruti** [comment]
This is only true for Fabritone.
I think it's better to focus on #36 and solve this(#41) issue in that way...

**Comment by adrisj7** [comment]
Well not really, the issue is that fabritone/baritone would be included as a SEPARATE jar. Your mods folder should look like this:
```
mods
- alto-clef-SNAPSHOT.jar
- baritone-1.16.jar
- other potential jar files also must be put here!
```

However, when you run `build` in the altoclef project, it only generates the `alto-clef-SNAPSHOT.jar`, not the other jars. Doesn't matter if the separate project is using fabritone or baritone. The user should have easy access to those jars when building, otherwise every time they want to test it online they have to open up the project that can build `baritone-1.16.jar` AND also locate all the other dependencies that I may add in the future. That's no fun, and I'd like to fix that before making an official build/release.

**Comment by adrisj7** [comment]
Shadow works with extra libraries, but the baritone jar is still needed and I couldn't figure out how to package it together.

Will abandon this idea for now, as external libraries can now be added without changing the build process.
