### ISSUE TITLE
Allow to travel between dimensions using @goto

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#52]
## Your Idea
Allow to travel between dimensions using `@goto`. A few examples:

`@goto 0 100 0` = get to 0 100 0 in the current dimention
`@goto 0 100 0 nether` = get to 0 100 0 in the nether
`@goto nether 0 100 0` = get to 0 100 0 in the nether
`@goto nether` = get to the nether

**Comment by adrisj7** [comment]
Sup boss, [Just merged your stuff](https://github.com/toccatina/altoclef/commit/96c9dc237011d074a47d2de127bbceabea5d9cdb) and it works.

Examples:
`@goto 0 100 0 nether`
`@goto 0 0 nether`
`@goto nether`
The dimension must come at the end, so `@goto nether 0 100 0` won't work, but I think for consistency that's valid.
