### ISSUE TITLE
Make Settings easier to understand/change

### ISSUE THREAD

**Issue by adrisj7** [toccatina/altoclef#53]
## Your Idea

Include a txt file next to the settings file explaining each parameter

**Comment by TheBlueBurger** [comment]
Maybe make a baritone-like in-game settings menu

**Comment by adrisj7** [comment]
This is p low priority tbh since Settings.java contains documentation within itself.

**Comment by NoobMaster420-69** [comment]
https://github.com/gaucho-matrero/altoclef github
