### ISSUE TITLE
Hunt endermen in the nether instead

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#55]
## Your Idea
There is a biome in the nether where endermen are really common, maybe craft a chest before going to the nether, place it in the nether, and then find the biome where endermen spawn and hunt there

**Comment by adrisj7** [comment]
Good idea, but for speedrunning the best bet is probably to switch to version 1.16.1 and do piglin bartering. Bartering is already programmed, so all we need to do is downgrade the versin in a speedrun branch or something.
