### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.entity.mob.HoglinEntity cannot be cast to net.minecraft.entity.mob.HostileEntity

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#57]
## Bug Description
Throws error while being attacked by a Hoglin
## Steps to Reproduce (as best as you can)
Get a Hoglin to attack you
## Expected Behavior
Doesnt crash
## Actual Behavior
Crashes
[crash-2021-06-15_18.07.39-client.txt](https://github.com/toccatina/altoclef/files/6657094/crash-2021-06-15_18.07.39-client.txt)

**Comment by adrisj7** [comment]
Fixed in [Commit afac9e18ef311c21fa9c3f8426b79b374b51f92a](https://github.com/toccatina/altoclef/commit/afac9e18ef311c21fa9c3f8426b79b374b51f92a).

**Comment by adrisj7** [comment]
(This introduced a bug where the bot did not fear/run away from hoglins, but that was fixed in [the next commit](https://github.com/toccatina/altoclef/commit/2b1cff32a3d8a0c64088a51bb52ea10e8b3c6fec), things should now be working as intended.)
