### ISSUE TITLE
Uses Right Click to place when settings are different

### ISSUE THREAD

**Issue by MyUsernamee** [toccatina/altoclef#59]
## Bug Description
If you change your place and break settings Alto Clef will try to use the default controls to place the block.

## Steps to Reproduce (as best as you can)
Change Place settings in controls in minecraft then try to get diamond.

## Expected Behavior
IT places the block with the user control

## Actual Behavior
It places with default controls

**Comment by adrisj7** [comment]
Should be fixed in [Commit 997cfd892664d6b01d162e1e3e00f5b4150a6345](https://github.com/toccatina/altoclef/commit/997cfd892664d6b01d162e1e3e00f5b4150a6345), thank you for contributing!
