### ISSUE TITLE
@stop does not stop baritone

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#60]
## Bug Description
@stop does not stop baritone
## Steps to Reproduce (as best as you can)
Execute a task, then run `@stop`
## Expected Behavior
Baritone and altoclef stops
## Actual Behavior
Baritone doesn't stop
## Crashlogs (if applicable)
None

**Comment by adrisj7** [comment]
This is a legitimate bug.

There are a lot of tasks to execute, is there a specific command that you ran? What part of the command were you on?

We _could_ fix this by simply running `onLostControl` on every single baritone process to make sure it's all stopped, but that would only be a duct tape solution, it would not fix the bug. This means a task isn't stopping baritone in its `onStop` method when it should, and it would be great to figure out which task that is.

**Comment by adrisj7** [comment]
I "think" I found the issue you encounteded: [In GetToBlockTask](https://github.com/toccatina/altoclef/blob/1b37bde2f9ea55a5a37c15258088cff600ec5d69/src/main/java/adris/altoclef/tasks/GetToBlockTask.java#L34). I should call `super.onStop` there where the baritone goal is stopped, but I don't.

But to deal with the problem as a whole I will add the duct tape patch (stop all processes on `@stop`) but **also** print a warning if baritone doesn't stop, so it can be made as an issue.
