### ISSUE TITLE
AltoClef Bucket Save fails: places water on wrong block if there is a height difference

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#61]
## Bug Description
AltoClef places water on wrong block if there is a height difference
## Steps to Reproduce (as best as you can)
https://user-images.githubusercontent.com/58081413/123542386-a70a8100-d749-11eb-8e93-a1d136e8cbaa.mp4
## Expected Behavior
Bot places water on the top block
## Actual Behavior
Bot places water on the bottom block
## Crashlogs (if applicable)
None

**Comment by adrisj7** [comment]
Fixed with [commit c15258088cff600ec5d69](https://github.com/toccatina/altoclef/commit/1b37bde2f9ea55a5a37c15258088cff600ec5d69).

There still is the issue of the bot falling on non solid but placable blocks (like tall grass or signs), but that's very much a much bigger edge case.
