### ISSUE TITLE
Bot rebuilds portal

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#65]
## Bug Description
Some times, the bot will be almost finished with building a nether portal, then it comes up with the genius idea of breaking the obsidian and re-placing it for every block.
## Steps to Reproduce (as best as you can)
Get the bot to build a nether portal, happened once for me, and that time the bot had trouble with going to the portal (it got stuck) and then after about a minute it got out.
## Expected Behavior
The bot doesnt break the obsidian
## Actual Behavior
The bot breaks the obsidian
## Crashlogs and Screenshots (if applicable)
None

**Comment by adrisj7** [comment]
some recordings/screenshots or more info on how to reproduce reliably would be great, never seen this bug happen before

**Comment by TheBlueBurger** [comment]
I wasn't recording, and it was about a week ago

**Comment by adrisj7** [comment]
Will close cause a lot has happened since then, would need to happen again.
