### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by DarkReaper231** [toccatina/altoclef#70]
I know Baritone officially doesn't exist for 1.17 yet but there is pretty stable fork that works well enough on 1.17
https://github.com/MeteorDevelopment/baritone/tree/1.17

Could be worth it to consider updating it

**Comment by adrisj7** [comment]
Currently developing in the [1.17-port](https://github.com/toccatina/altoclef/tree/1.17-port) branch. Will close when that gets merged in.
