### ISSUE TITLE
Doesn't work well on sodium

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#71]
## Bug Description
Unable to walk using sodium at the same time
## Steps to Reproduce (as best as you can)
Install sodium then try to do anything
## Expected Behavior
It doesn't stuff
## Actual Behavior
It doesn't
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
I can't get any of these since it isn't my problem, someone on discord got this

**Comment by Kpoop123** [comment]
close. works in 1.17 with sodium 0.3.2 Build 7

**Comment by adrisj7** [comment]
Will close for now... But this might still be an issue so feel free to reopen.
