### ISSUE TITLE
Bot doesn't jump most of the time

### ISSUE THREAD

**Issue by PegasusPizza** [toccatina/altoclef#77]
## Bug Description
     The bot didn't jump most of the time and just stood before the blocks
## Steps to Reproduce (as best as you can)
     I created a new World in Minecraft 1.16.4 Fabric Version 1.11.6 and typed @get diamond in the chat to test the bot.
## Expected Behavior
      the bot gets diamonds
## Actual Behavior
     The bot got stuck on most of the jumps, even with auto jump enabled, he couldn't walk up blocks. But stacking himself up 
     was no problem. Baritone thought that he could walk up blocks, so he didn't try something else. It only said: Exploring failed in the chat. 
## Crashlogs and Screenshots (if applicable)
![2021-09-01_10 39 52](https://user-images.githubusercontent.com/56482661/131643774-9a319d96-d4b8-41b1-be2b-97f4a8ba37f6.png)

**Comment by adrisj7** [comment]
Just to be clear that you touched all the bases before submitting this, you didn't accidentally leave `assumeStep` on, right? https://github.com/cabaletta/baritone/blob/14178fcd14f245a21da0240c3fa4b507a8a00446/src/api/java/baritone/api/Settings.java#L125
