### ISSUE TITLE
1.16.5 update

### ISSUE THREAD

**Issue by SzymekNoob** [toccatina/altoclef#81]
## Version Update ##

I have an idea and a question.
The first question is whether there will be an update 1.16.5.
And the idea is to add ports from 1.8.8.

**Comment by adrisj7** [comment]
Focus will always be on the latest/most widely used version of Minecraft. Check the [README in the main repo page](https://github.com/toccatina/altoclef), we mention trying to use Multiconnect to get to earlier server versions.

**Comment by KMatias123** [comment]
wdym by ports *from* 1.8.8
