### ISSUE TITLE
Bot (sometimes) simply walks past diamonds even if he needs them.

### ISSUE THREAD

**Issue by Kpoop123** [toccatina/altoclef#85]
Bottom Text

**Comment by Ibex80** [comment]
They might have lava behind them, so the bot skips them.

**Comment by adrisj7** [comment]
^ yeah. If you encounter a case where it does skip good diamonds though, drop a seed and a spawn location below and the command you ran, hopefully it will be recreated.

**Comment by adrisj7** [comment]
Also it could be that the bot was simply skipping deepslate ore, as I hadn't catalogued that in yet. If that's the case then this issue is effectively closed.
