### ISSUE TITLE
"whisperFormats" isn't flexible enough to cover all message formats

### ISSUE THREAD

**Issue by Astatin3** [toccatina/altoclef#89]
## Bug Description:

Anything before the name is counted as part of the name
Anything directly after the name that is not a space character will get counted as part of the name

Example:
`"[Player -> me] follow"`
This doesn't work because there is a bracket before the player name

`"Player: follow"`
This doesn't work because there is a colon directly after the player name

## Recommended Fix:
I would recommend just removing any characters not part of MC names (A-Z, a-z, 0-9, _) from the name string:

This would look like
"[player_1]:" to "player_1"

**Comment by adrisj7** [comment]
You have to escape brackets with whisper formats.
`\[{from} -> {to}\] {message}`
Then it works. I could add a feature to automatically escape these though.

**Comment by adrisj7** [comment]
Added a note in [usage.md](https://github.com/toccatina/altoclef/blob/main/usage.md) mentioning you have to escape brackets and parenthesis. Not ideal but it will keep things consistent.
